# Get your APIKey from the MinecraftMarket panel
APIKey: randomstring
# Time between purchases and donors checks in minutes
CheckInterval: 5
# Ingame GUI shop commands
ShopCommands:
- "Shop"
- "Buy"
# Enable ingame GUI used by ShopCommands
UseGUI: true
# Enable recent donors signs
UseSigns: true
# Default skin to use on heads when account is cracked or request fails
DefaultHeadSkin: http://textures.minecraft.net/texture/456eec1c2169c8c60a7ae436abcd2dc5417d56f8adef84f11343dc1188fe138
# Log errors no need to activate this
Debug: false