name: MinecraftMarket
main: com.minecraftmarket.minecraftmarket.Market
version: 2.1.7
website: http://www.minecraftmarket.com
commands:
    mm:
        description: MinecraftMarket main command
        aliases: [minecraftmarket]